/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BudzetRouteImport } from './routes/budzet'
import { Route as KawalkiRouteImport } from './routes/kawalki'
import { Route as KodeksRouteImport } from './routes/kodeks'
import { Route as KredoRouteImport } from './routes/kredo'
import { Route as KronikaRouteImport } from './routes/kronika'
import { Route as KsiegaRouteImport } from './routes/ksiega'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as RozumieRouteImport } from './routes/rozumie'
import { Route as SkladkaRouteImport } from './routes/skladka'
import { Route as SlawaRouteImport } from './routes/slawa'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SztabRouteImport } from './routes/sztab'
import { Route as TablicaRouteImport } from './routes/tablica'
import { Route as TotRouteImport } from './routes/tot'
import { Route as ZborRouteImport } from './routes/zbor'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudzetRoute = BudzetRouteImport.update({
  id: '/budzet',
  path: '/budzet',
  getParentRoute: () => rootRouteImport,
} as any)
const KawalkiRoute = KawalkiRouteImport.update({
  id: '/kawalki',
  path: '/kawalki',
  getParentRoute: () => rootRouteImport,
} as any)
const KodeksRoute = KodeksRouteImport.update({
  id: '/kodeks',
  path: '/kodeks',
  getParentRoute: () => rootRouteImport,
} as any)
const KredoRoute = KredoRouteImport.update({
  id: '/kredo',
  path: '/kredo',
  getParentRoute: () => rootRouteImport,
} as any)
const KronikaRoute = KronikaRouteImport.update({
  id: '/kronika',
  path: '/kronika',
  getParentRoute: () => rootRouteImport,
} as any)
const KsiegaRoute = KsiegaRouteImport.update({
  id: '/ksiega',
  path: '/ksiega',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const RozumieRoute = RozumieRouteImport.update({
  id: '/rozumie',
  path: '/rozumie',
  getParentRoute: () => rootRouteImport,
} as any)
const SkladkaRoute = SkladkaRouteImport.update({
  id: '/skladka',
  path: '/skladka',
  getParentRoute: () => rootRouteImport,
} as any)
const SlawaRoute = SlawaRouteImport.update({
  id: '/slawa',
  path: '/slawa',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SztabRoute = SztabRouteImport.update({
  id: '/sztab',
  path: '/sztab',
  getParentRoute: () => rootRouteImport,
} as any)
const TablicaRoute = TablicaRouteImport.update({
  id: '/tablica',
  path: '/tablica',
  getParentRoute: () => rootRouteImport,
} as any)
const TotRoute = TotRouteImport.update({
  id: '/tot',
  path: '/tot',
  getParentRoute: () => rootRouteImport,
} as any)
const ZborRoute = ZborRouteImport.update({
  id: '/zbor',
  path: '/zbor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budzet': typeof BudzetRoute
  '/kawalki': typeof KawalkiRoute
  '/kodeks': typeof KodeksRoute
  '/kredo': typeof KredoRoute
  '/kronika': typeof KronikaRoute
  '/ksiega': typeof KsiegaRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/rozumie': typeof RozumieRoute
  '/skladka': typeof SkladkaRoute
  '/slawa': typeof SlawaRoute
  '/studio': typeof StudioRoute
  '/sztab': typeof SztabRoute
  '/tablica': typeof TablicaRoute
  '/tot': typeof TotRoute
  '/zbor': typeof ZborRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budzet': typeof BudzetRoute
  '/kawalki': typeof KawalkiRoute
  '/kodeks': typeof KodeksRoute
  '/kredo': typeof KredoRoute
  '/kronika': typeof KronikaRoute
  '/ksiega': typeof KsiegaRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/rozumie': typeof RozumieRoute
  '/skladka': typeof SkladkaRoute
  '/slawa': typeof SlawaRoute
  '/studio': typeof StudioRoute
  '/sztab': typeof SztabRoute
  '/tablica': typeof TablicaRoute
  '/tot': typeof TotRoute
  '/zbor': typeof ZborRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budzet': typeof BudzetRoute
  '/kawalki': typeof KawalkiRoute
  '/kodeks': typeof KodeksRoute
  '/kredo': typeof KredoRoute
  '/kronika': typeof KronikaRoute
  '/ksiega': typeof KsiegaRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/rozumie': typeof RozumieRoute
  '/skladka': typeof SkladkaRoute
  '/slawa': typeof SlawaRoute
  '/studio': typeof StudioRoute
  '/sztab': typeof SztabRoute
  '/tablica': typeof TablicaRoute
  '/tot': typeof TotRoute
  '/zbor': typeof ZborRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budzet'
    | '/kawalki'
    | '/kodeks'
    | '/kredo'
    | '/kronika'
    | '/ksiega'
    | '/login'
    | '/mapa'
    | '/rozumie'
    | '/skladka'
    | '/slawa'
    | '/studio'
    | '/sztab'
    | '/tablica'
    | '/tot'
    | '/zbor'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budzet'
    | '/kawalki'
    | '/kodeks'
    | '/kredo'
    | '/kronika'
    | '/ksiega'
    | '/login'
    | '/mapa'
    | '/rozumie'
    | '/skladka'
    | '/slawa'
    | '/studio'
    | '/sztab'
    | '/tablica'
    | '/tot'
    | '/zbor'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/budzet'
    | '/kawalki'
    | '/kodeks'
    | '/kredo'
    | '/kronika'
    | '/ksiega'
    | '/login'
    | '/mapa'
    | '/rozumie'
    | '/skladka'
    | '/slawa'
    | '/studio'
    | '/sztab'
    | '/tablica'
    | '/tot'
    | '/zbor'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudzetRoute: typeof BudzetRoute
  KawalkiRoute: typeof KawalkiRoute
  KodeksRoute: typeof KodeksRoute
  KredoRoute: typeof KredoRoute
  KronikaRoute: typeof KronikaRoute
  KsiegaRoute: typeof KsiegaRoute
  LoginRoute: typeof LoginRoute
  MapaRoute: typeof MapaRoute
  RozumieRoute: typeof RozumieRoute
  SkladkaRoute: typeof SkladkaRoute
  SlawaRoute: typeof SlawaRoute
  StudioRoute: typeof StudioRoute
  SztabRoute: typeof SztabRoute
  TablicaRoute: typeof TablicaRoute
  TotRoute: typeof TotRoute
  ZborRoute: typeof ZborRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budzet': {
      id: '/budzet'
      path: '/budzet'
      fullPath: '/budzet'
      preLoaderRoute: typeof BudzetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kawalki': {
      id: '/kawalki'
      path: '/kawalki'
      fullPath: '/kawalki'
      preLoaderRoute: typeof KawalkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kodeks': {
      id: '/kodeks'
      path: '/kodeks'
      fullPath: '/kodeks'
      preLoaderRoute: typeof KodeksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kredo': {
      id: '/kredo'
      path: '/kredo'
      fullPath: '/kredo'
      preLoaderRoute: typeof KredoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kronika': {
      id: '/kronika'
      path: '/kronika'
      fullPath: '/kronika'
      preLoaderRoute: typeof KronikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ksiega': {
      id: '/ksiega'
      path: '/ksiega'
      fullPath: '/ksiega'
      preLoaderRoute: typeof KsiegaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rozumie': {
      id: '/rozumie'
      path: '/rozumie'
      fullPath: '/rozumie'
      preLoaderRoute: typeof RozumieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skladka': {
      id: '/skladka'
      path: '/skladka'
      fullPath: '/skladka'
      preLoaderRoute: typeof SkladkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slawa': {
      id: '/slawa'
      path: '/slawa'
      fullPath: '/slawa'
      preLoaderRoute: typeof SlawaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sztab': {
      id: '/sztab'
      path: '/sztab'
      fullPath: '/sztab'
      preLoaderRoute: typeof SztabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tablica': {
      id: '/tablica'
      path: '/tablica'
      fullPath: '/tablica'
      preLoaderRoute: typeof TablicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tot': {
      id: '/tot'
      path: '/tot'
      fullPath: '/tot'
      preLoaderRoute: typeof TotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zbor': {
      id: '/zbor'
      path: '/zbor'
      fullPath: '/zbor'
      preLoaderRoute: typeof ZborRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudzetRoute: BudzetRoute,
  KawalkiRoute: KawalkiRoute,
  KodeksRoute: KodeksRoute,
  KredoRoute: KredoRoute,
  KronikaRoute: KronikaRoute,
  KsiegaRoute: KsiegaRoute,
  LoginRoute: LoginRoute,
  MapaRoute: MapaRoute,
  RozumieRoute: RozumieRoute,
  SkladkaRoute: SkladkaRoute,
  SlawaRoute: SlawaRoute,
  StudioRoute: StudioRoute,
  SztabRoute: SztabRoute,
  TablicaRoute: TablicaRoute,
  TotRoute: TotRoute,
  ZborRoute: ZborRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
